function load_images_gui
%% LOAD_IMAGES_GUI loads MT and MAP images

%% Global var
% Input (None)
% Output: 
global gb_mt_imgs gb_map_imgs;
global gb_mt_file gb_map_file;

mt_var = '';
map_var = '';
mt_img = [];
map_img = [];

%% GUI
h_load_images_fig = figure( ...
    'Name', 'Load Images', ...
    'NumberTitle', 'off', ...
    'Visible','off', ...
    'Position',[1 1 420 360], ...
    'Units', 'pixels', ...
    'Menubar','none', ...
    'Resize','off');
set(h_load_images_fig, ...
    'windowbuttondownfcn', '', ...
    'windowbuttonmotionfcn', '', ...
    'windowbuttonupfcn', '');

th = 40; % text height
tw = 180; % text width

% text and edit
% 1. MT file
h_mtfile_pbutt = uicontrol( ...
    'Parent', h_load_images_fig, ...
    'Style', 'pushbutton', ...
    'String', 'MT file', ...
    'FontSize', 24, ...
    'Position', [20, 300, tw, th], ...
    'Callback', @h_mtfile_pbutt_Callback);
h_mtfile_edit = uicontrol( ...
    'Parent', h_load_images_fig, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 12, ...
    'Position', [220, 300, tw, th], ...
    'Enable', 'on');

% 2. MAP file
h_mapfile_pbutt = uicontrol( ...
    'Parent', h_load_images_fig, ...
    'Style', 'pushbutton', ...
    'String', 'MAP file', ...
    'FontSize', 24, ...
    'Position', [20, 240, tw, th], ...
    'Callback', @h_mapfile_pbutt_Callback);
h_mapfile_edit = uicontrol( ...
    'Parent', h_load_images_fig, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 12, ...
    'Position', [220, 240, tw, th], ...
    'Enable', 'on');

% 1.1. MT file
h_mtvar_pbutt = uicontrol( ...
    'Parent', h_load_images_fig, ...
    'Style', 'pushbutton', ...
    'String', 'MT var', ...
    'FontSize', 24, ...
    'Position', [20, 150, tw, th], ...
    'Callback', @h_mtvar_pbutt_Callback);
h_mtvar_edit = uicontrol( ...
    'Parent', h_load_images_fig, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 12, ...
    'Position', [220, 150, tw, th], ...
    'Enable', 'on');

% 2.2. MAP file
h_mapvar_pbutt = uicontrol( ...
    'Parent', h_load_images_fig, ...
    'Style', 'pushbutton', ...
    'String', 'MAP var', ...
    'FontSize', 24, ...
    'Position', [20, 90, tw, th], ...
    'Callback', @h_mapvar_pbutt_Callback);
h_mapvar_edit = uicontrol( ...
    'Parent', h_load_images_fig, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 12, ...
    'Position', [220, 90, tw, th], ...
    'Enable', 'on');


% 3. ok push button
h_ok_pbutt = uicontrol( ...
        'Parent', h_load_images_fig, ...
        'Style', 'pushbutton', ...
        'String', 'OK', ...
        'Position', [165, 20, tw/2, th], ...
        'Callback', @h_ok_pbutt_Callback);

% Display the main window
movegui(h_load_images_fig, 'center');
set(h_load_images_fig, 'Visible', 'on');
uiwait(gcf);

%% Callbacks

function h_mtfile_pbutt_Callback(src,evt)
    [filename,pathname] = uigetfile( ...
        {'*.tif';'*.tiff';'*.*'}, ...
        'Choose MT File');
    if filename == 0
        return;
    end
    complete_filename = strcat(pathname, filename);
    gb_mt_file = complete_filename;
    update_text(h_mtfile_edit, gb_mt_file);
end

function h_mapfile_pbutt_Callback(src,evt)
    [filename,pathname] = uigetfile( ...
        {'*.tif';'*.tiff';'*.*'}, ...
        'Choose MAP File');
    if filename == 0
        return;
    end
    complete_filename = strcat(pathname, filename);
    gb_map_file = complete_filename;
    update_text(h_mapfile_edit, gb_map_file);
end

function h_mtvar_pbutt_Callback(src,evt)
    [mt_img,mt_var] = uigetvar;
    if isempty(mt_img)
        return;
    end
    gb_mt_file = '';
    update_text(h_mtvar_edit, mt_var);
end

function h_mapvar_pbutt_Callback(src,evt)
    [map_img,map_var] = uigetvar;
    if isempty(map_img)
        return;
    end
    gb_map_file = '';
    update_text(h_mapvar_edit, map_var);
end

function h_ok_pbutt_Callback(src,evt)
    if ~isempty(gb_mt_file) && ~isempty(mt_img)
        error('You can not use MT file and var at the same time');
        return;
    elseif ~isempty(gb_mt_file)
        gb_mt_imgs = tif_img_reader(gb_mt_file);
        gb_mt_imgs = double(gb_mt_imgs);
    elseif ~isempty(mt_img)
        gb_mt_imgs = double(mt_img);
    end
    if(~isempty(gb_mt_imgs) && numel(size(gb_mt_imgs))>3)
        warning('MT image has dimension greater than 3');
    end
    
    if ~isempty(gb_map_file) && ~isempty(map_img)
        error('You can not use MAP file and var at the same time');
        return;
    elseif ~isempty(gb_map_file)
        gb_map_imgs = tif_img_reader(gb_map_file);
        gb_map_imgs = double(gb_map_imgs);
    elseif ~isempty(map_img)
        gb_map_imgs = double(map_img);
    end
    if(~isempty(gb_map_imgs) && numel(size(gb_map_imgs))>3)
        warning('MAP image has dimension greater than 3');
    end

    close(h_load_images_fig);
end

%% helper function
function update_text(h_text, str)
    if ~iscell(str)
        set(h_text, 'String', str);
    else
        n_str = numel(str);
        all_str = '';
        for i = 1:n_str
            all_str = strcat(all_str, str{i}, sprintf('\n'));
        end
        % all_str = sprintf(all_str);
        set(h_text, 'String', all_str);
    end
end


end
