function setup_gui
%% SETUP_GUI setups the basic metric info of the images.

%% Global var
% Input (None)
% Output
global GB_NM_PER_PIXEL GB_TIME_INTERVAL;
GB_NM_PER_PIXEL = 0.0;
GB_TIME_INTERVAL = 0.0;

%% GUI
h_setup_fig = figure( ...
    'Name', 'Setup', ...
    'NumberTitle', 'off', ...
    'Visible','off', ...
    'Position',[1 1 420 200], ...
    'Units', 'pixels', ...
    'Menubar','none', ...
    'Resize','off');
set(h_setup_fig, ...
    'windowbuttondownfcn', '', ...
    'windowbuttonmotionfcn', '', ...
    'windowbuttonupfcn', '');

th = 40; % text height
tw = 180; % text width

% text and edit
% 1. nm_per_pixel
h_nmperpixel_text = uicontrol( ...
    'Parent', h_setup_fig, ...
    'Style', 'text', ...
    'String', 'nm/pixel', ...
    'FontSize', 24, ...
    'Position', [20, 140, tw, th]);
h_nmperpixel_edit = uicontrol( ...
    'Parent', h_setup_fig, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 24, ...
    'Position', [220, 140, tw, th], ...
    'Enable', 'on');

% 2. time_interval
h_timeinterval_text = uicontrol( ...
    'Parent', h_setup_fig, ...
    'Style', 'text', ...
    'String', 'interval(s)', ...
    'FontSize', 24, ...
    'Position', [20, 80, tw, th]);
h_timeinterval_edit = uicontrol( ...
    'Parent', h_setup_fig, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 24, ...
    'Position', [220, 80, tw, th], ...
    'Enable', 'on');

% 3. ok push button
h_ok_pbutt = uicontrol( ...
        'Parent', h_setup_fig, ...
        'Style', 'pushbutton', ...
        'String', 'OK', ...
        'Position', [165, 20, tw/2, th], ...
        'Callback', @h_ok_pbutt_Callback);

% Display the main window
movegui(h_setup_fig, 'center');
set(h_setup_fig, 'Visible', 'on');
uiwait(gcf);

%% Callbacks
function h_ok_pbutt_Callback(src,evt)
    val = get(h_nmperpixel_edit, 'String');
    if isempty(val)
        msgbox('Please Input nm/pixel Value');
        return;
    end
    GB_NM_PER_PIXEL = val;
    val = get(h_timeinterval_edit, 'String');
    if isempty(val)
        msgbox('Please Input time interval Value');
        return;
    end
    GB_TIME_INTERVAL = val;
    close(h_setup_fig);
end

end